baseURL = "/"
languageCode = "en-gb"
title = ""

enableRobotsTXT = true
disableAliases = true
disableKinds = ['tags', 'categories']
theme = "grid"

[params]
disallow_search_engines = false # set robots.txt to disallow everything
api = ""
cacheDomain = ""
tagline = ""
themeColor = "white"
pageTitlePrefix = ""

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]
page = ["HTML", "RSS", "JSON"]

# remove .{ext} from text/netlify
[mediaTypes."text/redirects"]
suffixes = [""]
delimiter = ""

[mediaTypes."text/headers"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/redirects"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/headers"
baseName = "_headers"
isPlainText = true
notAlternative = true
