baseURL = "/"
languageCode = "en-gb"
title = "Daniel Muller"

enableRobotsTXT = true
disableAliases = true
theme = "grid"

[params]
disallow_search_engines = false # set robots.txt to disallow everything
api = "https://d14cda90rt1dr5.cloudfront.net/api/"
cacheDomain = "d1tcprt12td1mo.cloudfront.net"
tagline = "Spare Time Amateur Photographer"

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
